name: ci

on:
  push:
  pull_request:

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.94.0
          components: clippy,rustfmt

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@cargo-nextest

      - name: Format
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Test
        run: cargo nextest run --workspace --all-features

      - name: Doc
        run: cargo doc --workspace --all-features --no-deps
